# Generated by Django 2.1.3 on 2019-05-31 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='energy',
            name='Solar_Elevation',
        ),
    ]
