# Generated by Django 2.2.1 on 2019-05-12 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='technology',
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.FilePathField(path='/static/energy'),
        ),
    ]
