# Generated by Django 2.2.1 on 2019-05-14 13:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20190512_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='energy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Month', models.PositiveIntegerField(default=8, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(10)])),
                ('Day', models.PositiveIntegerField(default=8, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(10)])),
                ('Hour', models.PositiveIntegerField(default=8, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(10)])),
                ('Age_lt_5', models.PositiveIntegerField(default=8, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(10)])),
                ('Age_range_5_to_18', models.PositiveIntegerField(default=8, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(10)])),
                ('Age_range_18_to_25', models.PositiveIntegerField(default=8, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(10)])),
                ('Age_range_25_to_65', models.PositiveIntegerField(default=8, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(10)])),
                ('Age_gt_65', models.PositiveIntegerField(default=8, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(10)])),
                ('Days_of_week', models.PositiveIntegerField(default=8, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(10)])),
                ('School_Day', models.PositiveIntegerField(default=8, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(10)])),
                ('Cloud_Cover_Fraction', models.PositiveIntegerField(default=8, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(10)])),
                ('Dew_point', models.PositiveIntegerField(default=8, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(10)])),
                ('Humidity_Fraction', models.PositiveIntegerField(default=8, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(10)])),
                ('Precipitable_Water', models.PositiveIntegerField(default=8, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(10)])),
                ('Tempreture', models.PositiveIntegerField(default=8, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(10)])),
                ('Sector_visibility', models.PositiveIntegerField(default=8, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(10)])),
                ('Sector_FOOD_SERVICE', models.PositiveIntegerField(default=8, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(10)])),
                ('Sector_Grocery', models.PositiveIntegerField(default=8, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(10)])),
                ('Sector_K12_school', models.PositiveIntegerField(default=8, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(10)])),
                ('Sector_Lodging', models.PositiveIntegerField(default=8, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(10)])),
                ('Sector_office', models.PositiveIntegerField(default=8, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(10)])),
                ('Sector_residental', models.PositiveIntegerField(default=8, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(10)])),
                ('Sector_STAND_ALONE_RETAIL', models.PositiveIntegerField(default=8, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(10)])),
            ],
        ),
    ]
