# Generated by Django 2.1.3 on 2019-05-24 09:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='solar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solar_Elevation', models.PositiveIntegerField(default=8, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(10)])),
                ('Cloud_Cover_Fraction', models.PositiveIntegerField(default=8, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(10)])),
                ('Dew_Point', models.PositiveIntegerField(default=8, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(10)])),
                ('Humidity_Fraction', models.PositiveIntegerField(default=8, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(10)])),
                ('Precipitation', models.PositiveIntegerField(default=8, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(10)])),
                ('Pressure', models.PositiveIntegerField(default=8, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(10)])),
                ('Temperature', models.PositiveIntegerField(default=8, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(10)])),
                ('Visibility', models.PositiveIntegerField(default=8, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(10)])),
                ('Wind_Speed', models.PositiveIntegerField(default=8, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(10)])),
            ],
        ),
    ]
