# Generated by Django 2.1.3 on 2019-05-24 10:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WindSpeed', models.PositiveIntegerField(default=8, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(10)])),
            ],
        ),
    ]
