# Generated by Django 2.1.3 on 2019-05-31 08:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WindSpeed', models.FloatField(default='', validators=[django.core.validators.MinValueValidator(0.2), django.core.validators.MaxValueValidator(30)])),
            ],
        ),
    ]
